# Generated by Django 4.2.5 on 2023-10-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0002_remove_quote_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.CharField(max_length=300),
        ),
    ]
